go-coverage:
  git-diff:
    mode: all
  exclude:
    # - '(^|/)3rd/'
    - '.*/example/[^/]+\.go$'
  rate: 0.65
  top: 10

go-cognitive:
  git-diff:
    mode: all
  exclude:
    # - '(^|/)3rd/'
    # - '.*/example/[^/]+\.go$'
  over: 15
  top: 10

go-format:
  git-diff:
    mode: all
  # exclude:
  #   - '(^|/)3rd/'
  # file-line: 1000
  # import: true
  # formated: true
  # package: true
  func-input-num: 4
  # func-output-num: 3
  # func-named-output: true
  # func-input-num-without-context: true
  # func-output-num-without-error: true
  # func-context-first: true
  # func-error-last: true
  # func-context-error-match: false
